# Generated by Django 2.2.9 on 2020-02-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boyband',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_lyrics', models.CharField(max_length=600)),
                ('song_name', models.CharField(max_length=200)),
                ('band_name', models.CharField(max_length=200)),
            ],
        ),
    ]
